export const CHANGE_PAGE = 'CHANGE_PAGE';
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRY_ID = 'GET_COUNTRY_ID';
export const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME';
export const SET_CONTINENT = 'SET_CONTINENT';
export const GET_COUNTRIES_BY_POPULATION = 'GET_COUNTRIES_BY_POPULATION';
export const COUNTRY_ERROR = 'COUNTRY_ERROR';